# Generated by Django 4.2.21 on 2025-11-15 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="shipingaddress",
            old_name="address",
            new_name="shiping_address",
        ),
        migrations.RenameField(
            model_name="shipingaddress",
            old_name="city",
            new_name="shiping_city",
        ),
        migrations.RenameField(
            model_name="shipingaddress",
            old_name="country",
            new_name="shiping_country",
        ),
        migrations.RenameField(
            model_name="shipingaddress",
            old_name="full_name",
            new_name="shiping_full_name",
        ),
        migrations.RenameField(
            model_name="shipingaddress",
            old_name="postal_code",
            new_name="shiping_postal_code",
        ),
        migrations.RenameField(
            model_name="shipingaddress",
            old_name="state",
            new_name="sshiping_tate",
        ),
    ]
