# Generated by Django 4.2.21 on 2025-11-15 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0002_rename_address_shipingaddress_shiping_address_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="shipingaddress",
            old_name="sshiping_tate",
            new_name="shiping_state",
        ),
    ]
