# Generated by Django 4.2.21 on 2025-11-17 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0003_rename_sshiping_tate_shipingaddress_shiping_state"),
    ]

    operations = [
        migrations.RenameField(
            model_name="shipingaddress",
            old_name="shiping_address",
            new_name="shipping_address",
        ),
        migrations.RenameField(
            model_name="shipingaddress",
            old_name="shiping_city",
            new_name="shipping_city",
        ),
        migrations.RenameField(
            model_name="shipingaddress",
            old_name="shiping_country",
            new_name="shipping_country",
        ),
        migrations.RenameField(
            model_name="shipingaddress",
            old_name="shiping_full_name",
            new_name="shipping_full_name",
        ),
        migrations.RenameField(
            model_name="shipingaddress",
            old_name="shiping_postal_code",
            new_name="shipping_postal_code",
        ),
        migrations.RenameField(
            model_name="shipingaddress",
            old_name="shiping_state",
            new_name="shipping_state",
        ),
        migrations.AddField(
            model_name="shipingaddress",
            name="shipping_email",
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
    ]
