# Generated by Django 4.2.21 on 2025-11-17 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "payment",
            "0004_rename_shiping_address_shipingaddress_shipping_address_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="shipingaddress",
            name="shipping_address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="shipingaddress",
            name="shipping_city",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="shipingaddress",
            name="shipping_country",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="shipingaddress",
            name="shipping_full_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="shipingaddress",
            name="shipping_postal_code",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="shipingaddress",
            name="shipping_state",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
