# Generated by Django 4.2.21 on 2025-11-25 15:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("payment", "0006_rename_shipingaddress_shippingaddress_p_order_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="p_order",
            old_name="ordered_at",
            new_name="date_ordered",
        ),
        migrations.RemoveField(
            model_name="p_order",
            name="product",
        ),
        migrations.RemoveField(
            model_name="p_order",
            name="quantity",
        ),
        migrations.AddField(
            model_name="p_order",
            name="date_shipped",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="p_order",
            name="shipped",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="p_order",
            name="amount_paid",
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name="p_order",
            name="email",
            field=models.EmailField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="p_order",
            name="full_name",
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="p_order",
            name="shipping_address",
            field=models.TextField(max_length=15000, null=True),
        ),
        migrations.AlterField(
            model_name="p_order",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
