# Generated by Django 4.2.21 on 2025-11-28 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0007_rename_ordered_at_p_order_date_ordered_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="p_order",
            name="shipped",
        ),
    ]
