# Generated by Django 4.2.21 on 2025-11-28 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0008_remove_p_order_shipped"),
    ]

    operations = [
        migrations.AddField(
            model_name="p_order",
            name="shipped",
            field=models.BooleanField(default=False),
        ),
    ]
