# Generated by Django 3.1.12 on 2026-02-01 10:31

from django.db import migrations
import djongo.models.fields
import payment.models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0010_auto_20251222_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='p_order',
            name='items',
            field=djongo.models.fields.ArrayField(default=list, model_container=payment.models.OrderItem),
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
