# Generated by Django 3.1.12 on 2026-08-18 12:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields
import payment.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payment', '0011_auto_20260201_1531'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='p_order',
            options={'ordering': ['-date_ordered'], 'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
        migrations.AlterModelOptions(
            name='shippingaddress',
            options={'ordering': ['-created_at'], 'verbose_name': 'Shipping Address', 'verbose_name_plural': 'Shipping Addresses'},
        ),
        migrations.RemoveField(
            model_name='p_order',
            name='shipped',
        ),
        migrations.AddField(
            model_name='p_order',
            name='date_delivered',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='p_order',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Order Notes'),
        ),
        migrations.AddField(
            model_name='p_order',
            name='order_number',
            field=models.CharField(default=payment.models.p_Order.generate_order_number, editable=False, max_length=50, unique=True, verbose_name='Order Number'),
        ),
        migrations.AddField(
            model_name='p_order',
            name='shipping_cost',
            field=payment.models.MongoDecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Shipping Cost'),
        ),
        migrations.AddField(
            model_name='p_order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='p_order',
            name='tax_amount',
            field=payment.models.MongoDecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Tax Amount'),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='p_order',
            name='amount_paid',
            field=payment.models.MongoDecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Amount Paid'),
        ),
        migrations.AlterField(
            model_name='p_order',
            name='email',
            field=models.EmailField(default='', max_length=250, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='p_order',
            name='full_name',
            field=models.CharField(default='', max_length=250, verbose_name='Full Name'),
        ),
        migrations.AlterField(
            model_name='p_order',
            name='items',
            field=djongo.models.fields.ArrayField(default=list, model_container=payment.models.OrderItem, verbose_name='Order Items'),
        ),
        migrations.AlterField(
            model_name='p_order',
            name='shipping_address',
            field=models.TextField(default='', max_length=1500, verbose_name='Shipping Address'),
        ),
        migrations.AlterField(
            model_name='p_order',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='shipping_address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='shipping_city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='shipping_country',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='shipping_email',
            field=models.EmailField(blank=True, max_length=100, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='shipping_full_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Full Name'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='shipping_postal_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Postal Code'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='shipping_state',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='State/Province'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shipping_addresses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='p_order',
            index=models.Index(fields=['user', 'date_ordered'], name='payment_p_o_user_id_f987e4_idx'),
        ),
        migrations.AddIndex(
            model_name='p_order',
            index=models.Index(fields=['status'], name='payment_p_o_status_da5c1c_idx'),
        ),
        migrations.AddIndex(
            model_name='p_order',
            index=models.Index(fields=['order_number'], name='payment_p_o_order_n_6615cc_idx'),
        ),
    ]
