# Generated by Django 4.2.21 on 2025-12-05 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_alter_order_product"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="old_cart",
        ),
    ]
